org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Release signing configuration
RELEASE_STORE_FILE=../../release-key.jks
RELEASE_STORE_PASSWORD=password123
RELEASE_KEY_ALIAS=releaseKey
RELEASE_KEY_PASSWORD=password123
