/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
  hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Benchmark`; params?: Router.UnknownInputParams; } | { pathname: `/api-test`; params?: Router.UnknownInputParams; } | { pathname: `/cpu-test`; params?: Router.UnknownInputParams; } | { pathname: `/image-test`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/location-test`; params?: Router.UnknownInputParams; } | { pathname: `/ram-test`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/ui-test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/constants/testConfig`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useLocationPermission`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/utils/csvExport`; params?: Router.UnknownInputParams; } | { pathname: `/utils/launchTime`; params?: Router.UnknownInputParams; } | { pathname: `/utils/navResult`; params?: Router.UnknownInputParams; };
  hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Benchmark`; params?: Router.UnknownOutputParams; } | { pathname: `/api-test`; params?: Router.UnknownOutputParams; } | { pathname: `/cpu-test`; params?: Router.UnknownOutputParams; } | { pathname: `/image-test`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/location-test`; params?: Router.UnknownOutputParams; } | { pathname: `/ram-test`; params?: Router.UnknownOutputParams; } | { pathname: `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/ui-test`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/testConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useLocationPermission`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/csvExport`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/launchTime`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/navResult`; params?: Router.UnknownOutputParams; };
  href: Router.RelativePathString | Router.ExternalPathString | `/Benchmark${`?${string}` | `#${string}` | ''}` | `/api-test${`?${string}` | `#${string}` | ''}` | `/cpu-test${`?${string}` | `#${string}` | ''}` | `/image-test${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/location-test${`?${string}` | `#${string}` | ''}` | `/ram-test${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | `/ui-test${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/constants/testConfig${`?${string}` | `#${string}` | ''}` | `/hooks/useLocationPermission${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | `/utils/csvExport${`?${string}` | `#${string}` | ''}` | `/utils/launchTime${`?${string}` | `#${string}` | ''}` | `/utils/navResult${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Benchmark`; params?: Router.UnknownInputParams; } | { pathname: `/api-test`; params?: Router.UnknownInputParams; } | { pathname: `/cpu-test`; params?: Router.UnknownInputParams; } | { pathname: `/image-test`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/location-test`; params?: Router.UnknownInputParams; } | { pathname: `/ram-test`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/ui-test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/constants/testConfig`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useLocationPermission`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/utils/csvExport`; params?: Router.UnknownInputParams; } | { pathname: `/utils/launchTime`; params?: Router.UnknownInputParams; } | { pathname: `/utils/navResult`; params?: Router.UnknownInputParams; };
    }
  }
}
